version: '3'

services:
  recognitionapi:
    image: recognitionapi
    container_name: recognition-api
    build: 
      context: ./entelectual-recognition-api
      dockerfile: ./Dockerfile
    ports: 
        - 3000:3000
    restart: always  