version: '3'

services:
  recognitionapi:
    image: recognitionapi
    container_name: recognition-api
    build: 
      context: ./entelectual-recognition-api
      dockerfile: ./Dockerfile
    ports: 
        - 3000:3000
    restart: always
    
  recognitionweb:
    depends_on:
        - recognitionapi
    image: recognitionweb
    container_name: recognition-web
    build: 
      context: ./entelectual-recognition-web
      dockerfile: ./Dockerfile
    ports: 
        - 3001:8080
    restart: always  