version: '3'

services:
  recognitiondatabase:
    image: "postgres"
    networks:
      - backend
    container_name: "recognition-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssword123
      - POSTGRES_DB=facerecognition
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always  

  recognitionapi:
    depends_on:
        - recognitiondatabase  
    image: recognitionapi
    networks:
      - backend
    container_name: recognition-api
    environment:
      - DATABASE_CONNECTION_STRING=postgres://postgres:P@ssword123@recognitiondatabase:5432/facerecognition
    build: 
      context: ./entelectual-recognition-api
      dockerfile: ./Dockerfile
    ports: 
        - 3000:3000
    restart: always
    
  recognitionweb:
    depends_on:
        - recognitionapi
    image: recognitionweb
    networks:
      - backend
    container_name: recognition-web
    build: 
      context: ./entelectual-recognition-web
      dockerfile: ./Dockerfile
    ports: 
        - 3001:8080
    restart: always  

networks:
  backend:
    driver: bridge

volumes:
    postgres-data:
        driver: local