const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const logger = require('morgan');

const cors = require('cors')
const helmet = require('helmet')

const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const modelRouter = require('./routes/model');
const eventRouter = require("./routes/event");
const attendeeRouter = require("./routes/attendee");

const app = express();

const options = {
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        title: 'API',
        version: '1.0.0',
        description: 'Test Express API with autogenerated swagger doc',
      },
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/*.js'],
  };
  
const specs = swaggerJsdoc(options);

app.use(helmet())
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use(cors())

app.use('/swagger', swaggerUi.serve, swaggerUi.setup(specs));
app.use('/v1/model', modelRouter);
app.use('/v1/event', eventRouter);
app.use('/v1/attendee', attendeeRouter);

module.exports = app;
